# Generated by Django 4.2 on 2023-07-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_remove_activity_genre_remove_activity_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='events'),
        ),
    ]
