# Generated by Django 3.2.20 on 2023-08-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='languages',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Kannada', 'Kannada'), ('Bengali', 'Bengali'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu')], default='Hindi', max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='languages',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Kannada', 'Kannada'), ('Bengali', 'Bengali'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu')], default='Hindi', max_length=128),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Fantacy', 'Fantacy'), ('Classic', 'Classic'), ('Comedy', 'Comedy'), ('Action', 'Action'), ('Adventure', 'Adventure')], default='Drama', max_length=128),
        ),
        migrations.AlterField(
            model_name='movie',
            name='languages',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Kannada', 'Kannada'), ('Bengali', 'Bengali'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu')], default='Hindi', max_length=128),
        ),
        migrations.AlterField(
            model_name='sport',
            name='category',
            field=models.CharField(choices=[('Cricket', 'Cricket'), ('Online Games', 'Online Games'), ('E Sports', 'E Sports'), ('Chess', 'Chess'), ('Football', 'Football'), ('Others', 'Others')], default='Cricket', max_length=128),
        ),
        migrations.AlterField(
            model_name='sport',
            name='languages',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Kannada', 'Kannada'), ('Bengali', 'Bengali'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu')], default='Hindi', max_length=128),
        ),
    ]
