# Generated by Django 3.2.20 on 2023-08-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0013_auto_20230826_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdbID',
            new_name='showID',
        ),
        migrations.AddField(
            model_name='activity',
            name='showID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='showID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='showID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
