# Generated by Django 3.2.20 on 2023-09-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0014_auto_20230826_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('movie', 'movie'), ('sport', 'sport'), ('event', 'event'), ('activity', 'activity')], default='movie', max_length=128),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('movie', 'movie'), ('sport', 'sport'), ('event', 'event'), ('activity', 'activity')], default='movie', max_length=128),
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('movie', 'movie'), ('sport', 'sport'), ('event', 'event'), ('activity', 'activity')], default='movie', max_length=128),
        ),
        migrations.AddField(
            model_name='sport',
            name='type',
            field=models.CharField(choices=[('movie', 'movie'), ('sport', 'sport'), ('event', 'event'), ('activity', 'activity')], default='movie', max_length=128),
        ),
    ]
